### ISSUE TITLE
How can I dump the ue4 dumper so of Apex Legends/1.1.839.46

### ISSUE THREAD

**Issue by stayperfection** [Real-Ascarre/UE4-Apk-Dumper#3]
I use the method of the following link, the so from the dumper cannot be offset in ida, it seems that it is because of confusion?

https://github.com/kp7742/UE4Dumper
--Lib Dump Args--------------------------------------------------------------------------
   --lib                               Dump libUE4.so from Memory
   --raw(Optional)                     Output Raw Lib and Not Rebuild It
   --fast(Optional)                    Enable Fast Dumping(May Miss Some Bytes in Dump)

How did you dump the so? Can you share the so of your dumper game Apex Legends/1.1.839.46? I found what I wanted from the so dumped by the "kp7742/UE4Dumper" method, maybe because of function confusion? Maybe it's because of my dumper's fault? thanks for answer

(I can use the so from the PUBG dumper, and the "kp7742/UE4Dumper" method is also used)

**Comment by Real-Ascarre** [comment]
If you using this project then all u need to do is bypass the signature check, add the apk into apex  ( only dex and lib) then click on lib dump option.
By default it will dump lib in fast method but u can dump whole lib noted as Full Dump...
On Ue4dumper you need to put args (package name, --lib )

**Comment by stayperfection** [comment]
> If you using this project then all u need to do is bypass the signature check, add the apk into apex ( only dex and lib) then click on lib dump option. By default it will dump lib in fast method but u can dump whole lib noted as Full Dump... On Ue4dumper you need to put args (package name, --lib )


Do you have a dumper so out, can you send me a copy?

**Comment by stayperfection** [comment]
> If you using this project then all u need to do is bypass the signature check, add the apk into apex ( only dex and lib) then click on lib dump option. By default it will dump lib in fast method but u can dump whole lib noted as Full Dump... On Ue4dumper you need to put args (package name, --lib )

i need to find
"bool LineOfSightTo(const Actor* Other, Vector ViewPoint, bool bAlternateChecks);// 0x6805154"

The offset of this function, I can't find the offset from dumper so, so seems to be encrypted, if you can help me find out what the offset is?

**Comment by Real-Ascarre** [comment]
Search in the sdk i uploaded its there....

https://raw.githubusercontent.com/Real-Ascarre/UE4-Apk-Dumper/master/Dumped%20SDKs/Pubg%20Mobile/2.1.0/SDKW.txt

**Comment by Real-Ascarre** [comment]
Check in the sdks i uploaded
Apex 32 bit....

https://github.com/Real-Ascarre/UE4-Apk-Dumper/blob/master/Dumped%20SDKs/Apex%20Legends/1.1.839.46/SDKW%20-%2032%20Bit.txt

**Comment by Real-Ascarre** [comment]
Hope you found your offset by now. Best of Luck.
