### ISSUE TITLE
32 bit dump

### ISSUE THREAD

**Issue by lynxjinx** [Real-Ascarre/UE4-Apk-Dumper#4]
Can you try dumping ark mobile 32x? I tried with steps but could not get it to work, thank you🙏

**Comment by Real-Ascarre** [comment]
I haven't updated the offsets for Ark Mobile also kind of busy with Life RN, so I need to find them first. Once find I will upload.

**Comment by Real-Ascarre** [comment]
sorry for taking forever, you can load the lib in ida pro and get the offsets in the exports tab. the ue version is 4.15 as far i remember and there is no basic protection.
