### ISSUE TITLE
Working example of offsets.h for apex?

### ISSUE THREAD

**Issue by rustypicker** [Real-Ascarre/UE4-Apk-Dumper#5]
Hey bro
Im stuck trying to find my way back to gworld and gnames from the Apex Legends SDK you posted 

Do you mind sharing the offsets header file you used to dump the SDK?

Or even just 64bit gworld and gnames would be great :)

**Comment by Real-Ascarre** [comment]
Apex Legends 64 bit

GWorld = 0xB7844B0;
GNames = 0xB60C740;
GUObjectArray = 0xB626978;

**Comment by rustypicker** [comment]
Thank you bro!

**Comment by silentninjabee** [comment]
> Apex Legends 64 bit
> 
> GWorld = 0xB7844B0; GNames = 0xB60C740; GUObjectArray = 0xB626978;


Hey bro. Have you any experience with bypassing the anticheat, root/jailbreak detection, and integrity checks that this game is using? 
They are using a custom version of anogsdk (just like pubgm) and also using tencent's BUGLYSDK to report back to the developer and slap those 10year ban's down

**Comment by Real-Ascarre** [comment]
It is easy to bypass just reverse the function causing the check for dex files. I won't public the method or func offset. This repo is based on dumping and generating sdk only.
